### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by rasmusvan** [perses/website#29]
I use Mac. Starting the website locally is not as trivial as git clone'ing the repo and running `podman-compose up -d`

I personally didn't have podman before so I installed it (and podman-compose) with brew. Following the README, I didn't get it to work as I got the following errors:
```
Error: statfs /run/user/1000/podman/podman.sock: no such file or directory
Error: no container with name or ID "website_traefik_1" found: no such container
```

**Comment by Nexucis** [comment]
Hello,

That's not a big surprised that it doesn't work. This repository contain the docker-compose file that is running the demo and the Perses website. All files and configurations have been created to be able to work on the VM where it is hosted.

The goal was not to be able to run it locally but to run it on the VM.

The README is accurate when you want to deploy the website and the demo on the VM.

Perhaps we should add more details on the README to precise it cannot work locally.

**Comment by rasmusvan** [comment]
Thank you for your answer!

I'll use this as a chance to ask a question which I have been stuck on for the past week. 

I'm trying to implement a Perses dashboard on my react app, which displays TimeCharts from a Prometheus datasource. The thing is, I must implement it in a way that I can provide the dashboard configuration in a manifest file (YAML, JSON). Is creating dashboards in other application from manifest files something that can be done at this stage of development and if so, could you please direct me to the documentation for that or write it here?

**Comment by rasmusvan** [comment]
I closed the issue accidentally. Please see my question in the comment above

**Comment by Nexucis** [comment]
closing this issue as it has nothing to do with `website`. I will answer your question in https://github.com/perses/perses/issues/2108
