### ISSUE TITLE
Authentication section is broken

### ISSUE THREAD

**Issue by rasmusvan** [perses/website#30]
On the perses.dev website under the section Docs -> Perses -> v0.47.0 -> Design-Docs -> Auhtentication below "Login from external OIDC or OAuth2.0 provider with interactive flow, through WEB UI. " title, there is a bunch of text that is seemingly gibberish and most likely formatted wrong. If this is the expected output, I apologize for wasting your time.

<img width="355" alt="image" src="https://github.com/user-attachments/assets/442c221d-5f05-425e-af9d-1b741976a548">

**Comment by Nexucis** [comment]
yes there is an issue with the generation of these schemas. I had to deactivate it because it prevents the website to start. It's perhaps related to this issue: https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/kroki.2Eio.20returns.20400.20on.20Mermaid.20diagrams

**Comment by Nexucis** [comment]
fix with the new website
